CREATE DATABASE LUTECH;
 USE LUTECH;

-- CRIANDO A PRIMEIRA TABELA CHAMADA PROJETOS, COM TODOS OS ATRIBUTOS
    
CREATE TABLE CLIENTE (
    NOME_CLIENTE VARCHAR(50)PRIMARY KEY NOT NULL,
    ID_PEDIDO DECIMAL(32),
    END_PROJ VARCHAR(50),
    TEL_PROJ DECIMAL(11),
    TEL2_PROJ DECIMAL(11),
    
    FOREIGN KEY (ID_PEDIDO) REFERENCES MANUTENCAO(ID_PEDIDO)
);

-- CRIANDO A SEGUNDA TABELA CHAMADA DISP_ELETRONICO, COM TODOS OS ATRIBUTOS
CREATE TABLE PEÇA_HARDWARE(
	STATUS_COMPRA CHAR(3),
    TIPO_DISP VARCHAR(10) PRIMARY KEY,
    ID_PEDIDO DECIMAL(32),

    FOREIGN KEY(ID_PEDIDO) REFERENCES MANUTENCAO(ID_PEDIDO)
);

-- CRIANDO A TERCEIRA TABELA CHAMADA MANUTENCAO, COM 1 ATRIBUTO APENAS
CREATE TABLE MANUTENCAO(
	ID_PEDIDO DECIMAL(32) PRIMARY KEY,
    NOME_CLIENTE VARCHAR(50),
    STATUS_PROJ CHAR(3),
    TIPO_DISP VARCHAR (10),
-- DATA_ENTREGA FUTURO
    
    FOREIGN KEY(NOME_CLIENTE) REFERENCES CLIENTE(NOME_CLIENTE)
  
);

-- CRIANDO A QUARTA TABELA CHAMADA PREÇOS, COM 1 

CREATE TABLE PRECOS(
    SERVIÇOS DECIMAL(1000.00)
);

-- INSERINDO DADOS DENTRO DA TABELA "CLIENTE"
INSERT INTO CLIENTE (NOME_CLIENTE, ID_PROJ, END_PROJ, TEL_PROJ) -- STATUS_PROJ)
VALUES("Lívia Sarruf", "1","", 3299570234);

INSERT INTO CLIENTE (NOME_CLIENTE, ID_PROJ, END_PROJ, TEL_PROJ) -- STATUS_PROJ)
VALUES ("Evandro_Miguel","2", "Santa_Luzia", 32984100646);
-- INSERINDO DADOS DENTRO DA TABELA "PROJETOS"
INSERT INTO CLIENTE (NOME_CLIENTE, ID_PROJ, END_PROJ, TEL_PROJ) -- STATUS_PROJ)
VALUES ("Tayná","3","Recanto_dos_Lagos", 32984217318);
-- INSERINDO DADOS DENTRO DA TABELA "PROJETOS"
INSERT INTO CLIENTE (NOME_CLIENTE, ID_PROJ, END_PROJ, TEL_PROJ) -- STATUS_PROJ)
VALUES ("Nathalia","4", "Morro da Glória",32999053039);





SHOW TABLES; -- COMANDO PARA VER AS TABELAS EXISTENTES
SHOW DATABASES; -- COMANDO PRA VER OS BANCOS DE DADOS EXISTENTES

--  ALTER TABLE projetos ADD PRIMARY KEY(INDE_PROJ); -- ADICIONANDO UMA CHAVE PRIMÁRIA DENTRO DA TABELA PROJETOS
--  ALTER TABLE disp_eletronico ADD PRIMARY KEY (ID_DIS); -- ADICIONANDO UMA CHAVE PRIMÁRIA DENTRO DA TABELA DISP_ELETRONICO

SET SQL_SAFE_UPDATES = 0; -- REMOVENDO A PROTEÇÃO DE SEGURANÇA DO BANCO DE DADOS

-- DELETE FROM PROJETOS WHERE STATUS_PROJ = "con";

ALTER TABLE PROJETOS
MODIFY COLUMN INDE_PROJ VARCHAR(50) NOT NULL;

ALTER TABLE PROJETOS
MODIFY COLUMN END_PROJ VARCHAR(50) NOT NULL;

UPDATE PROJETOS -- ANUNCIANDO O UPDATE NOS DADOS DA TABELA 
SET STATUS_PROJ = "con" -- TROCANDO O ÚNICO DADO QUE EU QUERO
WHERE INDE_PROJ = "Lívia Sarruf";  -- ESPECIFICANDO ONDE EU QUERO QUE SEJA TROCADO

USE LUTECH;
UPDATE PROJETOS
SET STATUS_PROJ = "con"
WHERE INDE_PROJ = "Tayná";

UPDATE PROJETOS
SET STATUS_PROJ = "con"
WHERE INDE_PROJ = "Nathalia";

UPDATE PROJETOS
SET STATUS_PROJ = "con"
WHERE INDE_PROJ = "Evandro_Miguel";

USE LUTECH;
SELECT * FROM lutech.projetos;

